# **Assignment 1**  
# CSCI 2033 Sections 001 and 010: Elementary Computational Linear Algebra (spring 2024)

**Problem 0. Introduction to Colab and NumPy**

Ref:  https://numpy.org/doc/stable/user/quickstart.html


**Prerequisites**: You’ll need to know a bit of Python. For a refresher, see the [Python tutorial](https://docs.python.org/3/tutorial/).

Our coverage below is minimal and only serves as a warmup. We strongly suggest you work through the quickstart tutorial
https://numpy.org/doc/stable/user/quickstart.html

and other online resources, e.g.,

https://www.pythonlikeyoumeanit.com/module_3.html

to get comprehensive preparation.

### 0. import required module

In [2]:
import numpy as np
from numpy import linalg as LA

# Section 1: Vector

### 1. Vector creation
**You can create both (column) vectors and row vectors by using numpy 2d array**

This style will be used in the P1 and P2


In [3]:
# row vector (Matrix with single row)
# matrix need double bracket.
# Inner bracket is row; Outer bracket is collecting multiple rows.
v_row = np.array([[3, 4]])
print("row vector v_row is {}.".format(v_row))
print("the shape of v_row is {}".format(v_row.shape))
print()
# column vector
v_col = np.array([[3],[4]])
print("column vector v_col is {}".format(v_col))
print("the shape of v_col is {}".format(v_col.shape))
print()
# Matrix
m_example = np.array([[3,2],[1,4]])
print("Check the difference with matrix")
print("Example for matrix \n {}".format(m_example))

row vector v_row is [[3 4]].
the shape of v_row is (1, 2)

column vector v_col is [[3]
 [4]]
the shape of v_col is (2, 1)

Check the difference with matrix
Example for matrix 
 [[3 2]
 [1 4]]


In [4]:
v = np.array([[3],[1],[2]])
w = np.array([[1],[2],[3],[4],[5],[6]])

### 2. Indexing

Get the first element from the above array:


In [5]:
tmp = w[0:1]
print("first element of w is {}".format(tmp))

first element of w is [[1]]


Get the first three elements

In [6]:
tmp = w[:3]
print("first three elements of w is \n{}".format(tmp))

first three elements of w is 
[[1]
 [2]
 [3]]


Get the last two elements from the above array:


In [7]:
tmp = w[-2:]
print("last two elements of w is \n{}".format(tmp))

last two elements of w is 
[[5]
 [6]]


Get the third to fifth elemnt

In [8]:
tmp = w[2:5]
print("third to fifth elements of w is \n{}".format(tmp))

third to fifth elements of w is 
[[3]
 [4]
 [5]]


### 4. Vector addition

In [9]:
v1 = np.array([[1], [2], [3]])
v2 = np.array([[1], [5], [-1]])
tmp = v1 + v2
print("v1 + v2 = \n{}".format(tmp))
print()

v1 + v2 = 
[[2]
 [7]
 [2]]



In [10]:
tmp = v1-v2
print("v1 - v2 = \n{}".format(tmp))

v1 - v2 = 
[[ 0]
 [-3]
 [ 4]]


### 5. Scalar Multiplication

In [11]:
tmp = 2*v
print("2*v = \n{}".format(tmp))

2*v = 
[[6]
 [2]
 [4]]


In [12]:
tmp = 0.5*w
print("0.5*w = \n{}".format(tmp))

0.5*w = 
[[0.5]
 [1. ]
 [1.5]
 [2. ]
 [2.5]
 [3. ]]


###6. Linear Combination

In [13]:
v1 = np.array([[1], [2], [3]])
v2 = np.array([[1], [5], [-1]])
tmp = 5*v1 + 6*v2
print("5v1 + 6v2 = \n{}".format(tmp))
print()

5v1 + 6v2 = 
[[11]
 [40]
 [ 9]]



In [14]:
tmp = 5*v1 - 6*v2
print("5v1 - 6v2 = \n{}".format(tmp))
print()

5v1 - 6v2 = 
[[ -1]
 [-20]
 [ 21]]



### 7. Inner product

In [15]:
# for 2D-array version of vectors, to call inner,
# we have to get their flattened versions first (Edit: Feb 12 by Ju)
v1 = np.array([[1], [2], [3]])
v2 = np.array([[1], [5], [-1]])
v1f = v1.flatten()
v2f = v2.flatten()
tmp = np.inner(v1f,v2f)
print("<v1,v2> = {}".format(tmp))


<v1,v2> = 8




### 8. Norm




In [16]:
tmp = LA.norm(v)
print("||v|| = {}".format(tmp))

||v|| = 3.7416573867739413


Another method for getting norm

In [17]:
vf = v.flatten()
inner_prod = np.inner(vf,vf)
tmp = np.sqrt(inner_prod)
print("||v|| = {}".format(tmp))

||v|| = 3.7416573867739413



### 9. Distance between two points



In [18]:
p1 = np.array([[1],[2], [3]])
p2 = np.array([[1], [5], [-1]])

# distance is the norm of difference
tmp = LA.norm(p1-p2)
print("||v|| = {}".format(tmp))

||v|| = 5.0


### 10. Cosine Similarity two vectors

In [19]:
u1 = np.array([[0], [2]])
u2 = np.array([[1], [0]])
u1f = u1.flatten()
u2f = u2.flatten()
tmp = np.inner(u1f, u2f)/(LA.norm(u1)*LA.norm(u2))
print("cos_similarity = {}".format(tmp))

cos_similarity = 0.0


In [20]:
u1 = np.array([[1], [0]])
u2 = np.array([[1], [1]])
u1f = u1.flatten()
u2f = u2.flatten()
tmp = np.inner(u1f,u2f)/(LA.norm(u1)*LA.norm(u2))
print("cos_similarity = {}".format(tmp))

cos_similarity = 0.7071067811865475


# Section 2: Matrix

### 1. Matrix creation

In [21]:
A1 = np.array([[1, 2], [3, 4]])
print("A1 = \n{}".format(A1))
print("Shape of Matrix A1 is {}".format(A1.shape))

A1 = 
[[1 2]
 [3 4]]
Shape of Matrix A1 is (2, 2)


In [22]:
A2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("A2 = \n{}".format(A2))
print("Shape of Matrix A2 is {}".format(A2.shape))

A2 = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape of Matrix A2 is (3, 3)


### 2. Matrix indexing

**The index of each dimention must be an 1d array**

In [23]:
tmp = A2[1:2,:]
print("Second row of A2 is {}".format(tmp))

Second row of A2 is [[4 5 6]]


In [24]:
tmp = A2[2:3,2:3]
print("Entry A(3,3) = {}".format(tmp))

Entry A(3,3) = [[9]]


In [25]:
tmp = A2[:,0:1]
print("first col of A2 is \n{}".format(tmp))

first col of A2 is 
[[1]
 [4]
 [7]]


In [26]:
tmp = A2[:,:]
print("A2 is \n{}".format(tmp))

A2 is 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### 3. Matrix-Matrix Multiplication

In [27]:
A3 = np.array([[1, 2, 3], [5, 6, 7]])
A4 = np.array([[1,2], [3,4],[5,6]])

In [28]:
# First thing we recommend you to do is check the shape of the two matrices
# you want to perform multication with before you start to do multiplication
print("A3's Shape is {}".format(A3.shape))
print("A4's Shape is {}".format(A4.shape))
print()

tmp = np.matmul(A3,A4)
print("Result of A3 multply with A4 is \n{}".format(tmp))

A3's Shape is (2, 3)
A4's Shape is (3, 2)

Result of A3 multply with A4 is 
[[22 28]
 [58 76]]


**Another way to perform matrix-matrix multiplication is '@'**

In [29]:
tmp = A3 @ A4
print("Result of A3 multply with A4 is \n{}".format(tmp))

Result of A3 multply with A4 is 
[[22 28]
 [58 76]]


**Matrix-Vector Multiplication Example**

In [30]:
v = np.array([[1], [2], [4]])
print("Vector v is \n{}".format(v))
print()
print("Shape of Matrix A3 is \n{}".format(A3.shape))
print("Shape of Vector v is \n{}".format(v.shape))
tmp = A3 @ v
print("Result of A3 multply with v is \n{}".format(tmp))

Vector v is 
[[1]
 [2]
 [4]]

Shape of Matrix A3 is 
(2, 3)
Shape of Vector v is 
(3, 1)
Result of A3 multply with v is 
[[17]
 [45]]


### 4. Matrix Frobenius Norm

In [31]:
tmp = LA.norm(A1)
print("Norm of A1 = {}".format(tmp))

Norm of A1 = 5.477225575051661


Another way to get matrix norm

In [32]:
A1*A1
tmp = np.sqrt(np.sum(A1*A1))
print("Norm of A1 = {}".format(tmp))

Norm of A1 = 5.477225575051661


### 5. Matrix Transpose

In [33]:
print("Matrix A1 is \n{}".format(A1))
print()

A1T = A1.transpose()
print("Transposed Matrix A1^T is \n{}".format(A1T))
print()

# another way to do transpose
A1T = np.transpose(A1)
print("Transposed Matrix A1^T is \n{}".format(A1T))

Matrix A1 is 
[[1 2]
 [3 4]]

Transposed Matrix A1^T is 
[[1 3]
 [2 4]]

Transposed Matrix A1^T is 
[[1 3]
 [2 4]]


**Another way to perform matrix transpose is 'T'**

In [34]:
print("Matrix A2 is \n{}".format(A2))
print()

A2T = A2.T
print("Transposed Matrix A2^T is \n{}".format(A2T))

Matrix A2 is 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Transposed Matrix A2^T is 
[[1 4 7]
 [2 5 8]
 [3 6 9]]


### 6. Matrix Vector Concatenation

In [35]:
A = np.array([[1, 2, 3], [5, 6, 7], [8, 9, 10]])
b = np.array([[4],[8],[12]])


tmp = np.concatenate((A,b), axis = 1)
print("Concatenate A and b by column: \n{}".format(tmp))

print()

tmp = np.concatenate((A,b.T), axis = 0)
print("Concatenate A and b.T (row vector of b) by row: \n{}".format(tmp))


Concatenate A and b by column: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 8  9 10 12]]

Concatenate A and b.T (row vector of b) by row: 
[[ 1  2  3]
 [ 5  6  7]
 [ 8  9 10]
 [ 4  8 12]]


### 7. Initialize Spetial Matrices

In [36]:
A = np.zeros((2,3))
print("The 2x3 zero matrix generated is \n{}".format(A))

The 2x3 zero matrix generated is 
[[0. 0. 0.]
 [0. 0. 0.]]


In [37]:
A = np.ones((3,4))
print("The 3x4 one matrix generated is \n{}".format(A))

The 3x4 one matrix generated is 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [38]:
A = -np.ones((2,4))
print("The 2x4 matrix filled with -1 generated is \n{}".format(A))

The 2x4 matrix filled with -1 generated is 
[[-1. -1. -1. -1.]
 [-1. -1. -1. -1.]]
