### **Problem 1. Vector Operations**

In [1]:
import numpy as np
# fix  seed  for  reproducible  result. Please  do not  change  the  seed
rng = np.random.default_rng(20232033)
u = rng.random((10000 ,1))
v = rng.random((10000 ,1))
w = rng.random((10000 ,1))

**1.1 (1.5/5) Vector Indexing and Concatenation**

In [2]:
solution_1_a = u[2022]
solution_1_b = v[2022:2034]
solution_1_c = np.concatenate((v[:30], w[-100:]))

print(solution_1_a)
print()
print(solution_1_b)
print()
print(solution_1_c)

[0.60314211]

[[0.65678602]
 [0.62798177]
 [0.738143  ]
 [0.94811149]
 [0.55179546]
 [0.64332468]
 [0.13413764]
 [0.88390343]
 [0.81123801]
 [0.652259  ]
 [0.79811821]
 [0.51839792]]

[[0.83113392]
 [0.56120367]
 [0.40714254]
 [0.02460019]
 [0.01336789]
 [0.23740047]
 [0.35597481]
 [0.42937241]
 [0.74210288]
 [0.90285336]
 [0.02607093]
 [0.44963917]
 [0.53498762]
 [0.40634107]
 [0.2630476 ]
 [0.07118791]
 [0.70019422]
 [0.68242921]
 [0.69516576]
 [0.07349177]
 [0.81521685]
 [0.08946658]
 [0.58332285]
 [0.85940941]
 [0.59890161]
 [0.9019855 ]
 [0.67572507]
 [0.69824556]
 [0.21278617]
 [0.32064074]
 [0.85395778]
 [0.35686649]
 [0.82820314]
 [0.84829925]
 [0.41450186]
 [0.80222036]
 [0.291635  ]
 [0.96926886]
 [0.13700848]
 [0.47577132]
 [0.28188049]
 [0.37626924]
 [0.92659446]
 [0.76645543]
 [0.06965738]
 [0.16633979]
 [0.86241119]
 [0.61268771]
 [0.42784691]
 [0.52975043]
 [0.50287865]
 [0.78688485]
 [0.42783973]
 [0.85291338]
 [0.2349399 ]
 [0.51221287]
 [0.67892029]
 [0.84400258]
 [0.

**1.2 (1/5) Linear Combination**

In [3]:
solution_2_a = u + v + w

solution_2_b = 2*u + 3*v + 3*w

print(solution_2_a)
print()
print(solution_2_b)

[[2.08485402]
 [1.73665664]
 [1.50197551]
 ...
 [2.29001003]
 [1.9876794 ]
 [1.64777379]]

[[5.46122687]
 [4.67762199]
 [3.5376305 ]
 ...
 [6.3975946 ]
 [5.16694204]
 [4.42177553]]


**1.3 (1.5/5) Inner Product**

In [4]:
solution_3_a = np.inner(u.flatten(), u.flatten())

solution_3_b = np.inner((u - 2*v).flatten(), w.flatten())

solution_3_c = np.inner((3*u).flatten(), (2*v + w).flatten())

print(solution_3_a)
print()
print(solution_3_b)
print()
print(solution_3_c)

3334.1385686005715

-2485.1550842450188

22422.60043616603


**1.4 (1/5) Vector Norm**

In [5]:
solution_4_a = np.linalg.norm(u)

solution_4_b = np.linalg.norm(v + 3*w)

print(solution_4_a)
print()
print(solution_4_b)

57.74200003983731

219.0097026340124
