**Problem 1** Row Echelon Form and Rank

In [ ]:
import numpy as np

#Initializing matrix for test case a) in Problem 1.1
A1_square = np.array([[1, 0, 1, 0], [0, 0, 0, 0], [0, 0, 3, 1], [0, 0, 3, 0]], dtype=np.float64)

#Initializing matrix for test case b) in Problem 1.1
A2_square = np.array([[0, 1, 1], [2, 6, 4], [1, 1, 4]], dtype=np.float64)

**1.1** Row echelon form for square matrices by Gaussian elimination

In [ ]:
def GE_square(A, print_flag):
  R = A.copy()
  n = R.shape[0]
  pvt_list = []
  k = 0
  eps = np.finfo(np.float32).eps
  while k < n:
        # Check if the current subvector is all-zero
        while k < n and np.amax(np.abs(R[k:, k])) <= eps:
            k += 1
        if k == n:  # If all remaining subvectors are zero
            break

        # Find the first i such that abs(R[i, k]) is largest among abs(R[r, k])
        max_index = np.argmax(np.abs(R[k:, k])) + k
        R[[k, max_index], :] = R[[max_index, k], :]  # Exchange the two rows
        pvt_list.append(k)  # Add k to the list of pivot indices

        if print_flag:
            print("Current R after row exchange:")
            print(R)
            print("Pivot indices:", pvt_list)

        # Iteratively eliminate the rows below using the current row
        for j in range(k + 1, n):
            λ = R[j, k] / R[k, k]
            R[j, :] -= λ * R[k, :]

        if print_flag:
            print("Current R after elimination:")
            print(R)

        k += 1

  if print_flag:
        print("Final row echelon form of A:")
        print(R)
        print("Indices of pivot values:", pvt_list)

  return R, pvt_list

In [ ]:
R, pvt_idx_list = GE_square(A1_square, True)
# print out the row echelon form
print("row echelon form of A1_square:")
print(R)
# print out the indices of pivot values
print("Indices of pivot values:")
print(pvt_idx_list)

Current R after row exchange:
[[1. 0. 1. 0.]
 [0. 0. 0. 0.]
 [0. 0. 3. 1.]
 [0. 0. 3. 0.]]
Pivot indices: [0]
Current R after elimination:
[[1. 0. 1. 0.]
 [0. 0. 0. 0.]
 [0. 0. 3. 1.]
 [0. 0. 3. 0.]]
Current R after row exchange:
[[1. 0. 1. 0.]
 [0. 0. 0. 0.]
 [0. 0. 3. 1.]
 [0. 0. 3. 0.]]
Pivot indices: [0, 2]
Current R after elimination:
[[ 1.  0.  1.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  3.  1.]
 [ 0.  0.  0. -1.]]
Current R after row exchange:
[[ 1.  0.  1.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  3.  1.]
 [ 0.  0.  0. -1.]]
Pivot indices: [0, 2, 3]
Current R after elimination:
[[ 1.  0.  1.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  3.  1.]
 [ 0.  0.  0. -1.]]
Final row echelon form of A:
[[ 1.  0.  1.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  3.  1.]
 [ 0.  0.  0. -1.]]
Indices of pivot values: [0, 2, 3]
row echelon form of A1_square:
[[ 1.  0.  1.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  3.  1.]
 [ 0.  0.  0. -1.]]
Indices of pivot values:
[0, 2, 3]


In [ ]:
R, pvt_idx_list = GE_square(A2_square, True)
# print out the row echelon form
print("row echelon form of A2_square:")
print(R)
# print out the indices of pivot values
print("Indices of pivot values:")
print(pvt_idx_list)

Current R after row exchange:
[[2. 6. 4.]
 [0. 1. 1.]
 [1. 1. 4.]]
Pivot indices: [0]
Current R after elimination:
[[ 2.  6.  4.]
 [ 0.  1.  1.]
 [ 0. -2.  2.]]
Current R after row exchange:
[[ 2.  6.  4.]
 [ 0. -2.  2.]
 [ 0.  1.  1.]]
Pivot indices: [0, 1]
Current R after elimination:
[[ 2.  6.  4.]
 [ 0. -2.  2.]
 [ 0.  0.  2.]]
Current R after row exchange:
[[ 2.  6.  4.]
 [ 0. -2.  2.]
 [ 0.  0.  2.]]
Pivot indices: [0, 1, 2]
Current R after elimination:
[[ 2.  6.  4.]
 [ 0. -2.  2.]
 [ 0.  0.  2.]]
Final row echelon form of A:
[[ 2.  6.  4.]
 [ 0. -2.  2.]
 [ 0.  0.  2.]]
Indices of pivot values: [0, 1, 2]
row echelon form of A2_square:
[[ 2.  6.  4.]
 [ 0. -2.  2.]
 [ 0.  0.  2.]]
Indices of pivot values:
[0, 1, 2]


**1.2**  Row echelon form for rectangular matrices by Gaussian elimination

In [ ]:
#Initializing matrix for test case a) in Problem 1.2
A1_rect = np.array([[1, 2, 2, -1], [4, 8, 9, 6], [0, 3, 2, 9]], dtype=np.float64)

#Initializing matrix for test case b) in Problem 1.2
A2_rect = np.array([[1, 2, 3, 1, 2], [0, 4, 6, 0, 1], [2, 4, 8, 0, 0], [0, 1, 2, 0, 9]], dtype=np.float64)

In [85]:
def GE_rectangular(A, print_flag):
    R = A.copy()
    n = R.shape[0]  # number of rows in A
    m = R.shape[1]  # number of columns in A
    pvt_list = []
    k = 0
    eps = np.finfo(np.float32).eps

    if print_flag:
        print("Initial R:\n", R)

    # iterate through each row
    for r in range(n):
        # check if the subvector R[r:n, [k]] is zero
        while np.allclose(R[r:, k], 0, atol=eps):
            k += 1  # if all-zero, move to the next column
            if k == m:  # if we have checked all columns and all subvectors are zero
                if print_flag:
                    print("Final R:\n", R)
                    print("Pivot indices:", pvt_list)
                return R, pvt_list  # return the current R and pivot list

        # find the index i such that abs(R[i, k]) is largest among abs(R[r, k])
        i = np.argmax(np.abs(R[r:, k])) + r

        # exchange the rows
        R[[r, i]] = R[[i, r]]
        pvt_list.append(k)  # add k to the column list for pivots
        if print_flag:
            print("Current R:\n", R)
            print("Pivot indices:", pvt_list)

        # iteratively eliminate the rows below using the current row
        for j in range(r + 1, n):
            λ = R[j, k] / R[r, k]  # compute the multiplier
            R[j] -= λ * R[r]  # subtract λ times the r-th row from the j-th row
        if print_flag:
            print("Current R:\n", R)
            print("Pivot indices:", pvt_list)

    if print_flag:
        print("Final R:\n", R)
        print("Pivot indices:", pvt_list)
    return R, pvt_list

In [ ]:
R, pvt_idx_list = GE_rectangular(A1_rect, True)
# print out the row echelon form
print("row echelon form of A1_rect:")
print(R)
# print out the indices of pivot values
print("Indices of pivot values:")
print(pvt_idx_list)

In [ ]:
R, pvt_idx_list = GE_rectangular(A2_rect, True)
# print out the row echelon form
print("row echelon form of A2_rect:")
print(R)
# print out the indices of pivot values
print("Indices of pivot values:")
print(pvt_idx_list)

In [ ]:
#test your implementation on Eq. (3) (i.e., the worked square example) for debugging

R, pvt_idx_list = GE_rectangular(A1_square, True)
# print out the row echelon form
print("row echelon form of A1_square:")
print(R)
# print out the indices of pivot values
print("Indices of pivot values:")
print(pvt_idx_list)

In [ ]:
#test your implementation on Eq. (4) (i.e., the worked square example) for debugging

R, pvt_idx_list = GE_rectangular(A2_square, True)
# print out the row echelon form
print("row echelon form of A2_square:")
print(R)
# print out the indices of pivot values
print("Indices of pivot values:")
print(pvt_idx_list)

**1.3** Matrix rank and number of pivots

In [92]:
X = np.array([[1, 2, 4, 1], [3, 6, 12, 3], [4, 8, 16, 4]], dtype=np.float64)
Y = np.array([[1, 2, 4, 1], [3, 6, 12, 3], [4, 8, 16, 6]], dtype=np.float64)
Z = np.array([[1, 2, 4, 1], [3, 5, 12, 3], [4, 8, 16, 6]], dtype=np.float64)

# Compute REF and ranks
R_X, pivots_X = GE_rectangular(X, False)
R_Y, pivots_Y = GE_rectangular(Y, False)
R_Z, pivots_Z = GE_rectangular(Z, False)


# Count the number of pivots (rank)
rank_X = len(pivots_X)
rank_Y = len(pivots_Y)
rank_Z = len(pivots_Z)


Rank of X: 1
Dimension of null space of X: 3
Rank of Y: 2
Dimension of null space of Y: 2
Rank of Z: 3
Dimension of null space of Z: 1


In [93]:
from numpy.linalg import matrix_rank
#########Validate the answers about the matrices rank###########################
r_X = matrix_rank(X)
r_Y = matrix_rank(Y)
r_Z = matrix_rank(Z)
################################################################################

**Please double-click here and fill in the rank and dimension of nullspace of the these matrices**

rank(X) = 1, dimension of null(X) = 3

rank(Y) = 2, dimension of null(Y) = 2

rank(Z) = 3, dimension of null(Z) = 1
